// Generated by https://quicktype.io

export interface PokemonListResponde {
  count:    number;
  next:     string;
  previous?: string;
  results:  SmallPokemon[];
}

export interface SmallPokemon {
  name: string;
  url:  string;
  img: string;
  id: number;
}
